language: node_js
node_js: 8

cache:
  directories:
    - test/node_modules
    - test/android/build
    - test/ios/build


matrix:
  include:
  - language: objective-c
    os: osx
    osx_image: xcode10.2
    env:
    - REACT_NATIVE_VERSION=0.59.4
      PATH=$PATH:~/Library/Python/2.7/bin
    install:
    - npm install -g react-native-cli 
    - npm install -g detox-cli
    - export CODE_SIGNING_REQUIRED=NO
    - brew tap wix/brew
    - brew install applesimutils --HEAD
    - npm install        
    - cd test
    - npm install        
    - detox build --configuration ios.sim.release
    script:
    - CONF=ios.sim.release npx mocha Detox_helper_test.js

  - language: android
    env:
    - REACT_NATIVE_VERSION=0.59.4
    android:
    components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-26
    - sys-img-x86-android-28
    install:
    - yes | sdkmanager "platforms;android-28"    
    - echo y | sdkmanager "ndk-bundle"
    - echo y | sdkmanager "cmake;3.6.4111459"
    - echo y | sdkmanager --channel=3 --channel=1 "cmake;3.10.2.4988404"
    - echo y | sdkmanager "lldb;3.1"  
    - "export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle"
    - npm install -g react-native-cli 
    - npm install -g detox-cli
    - npm install        
    - cd test
    - npm install

    # Workaround until react android issue will be fixed - react-native: 0.55
    - npm run packager &
    - detox build --configuration android.emu.debug
    script:
    - CONF=android.emu.debug npx mocha Detox_helper_test.js


before_install:
- nvm install 10
