language: node_js
node_js: 8

matrix:
  include:
  - language: objective-c
    os: osx
    osx_image: xcode10.2
    env:
    - REACT_NATIVE_VERSION=0.59.4
      PATH=$PATH:~/Library/Python/2.7/bin
    install:
    - npm install -g react-native-cli 
    - npm install -g detox-cli
    - export CODE_SIGNING_REQUIRED=NO
    - brew tap wix/brew
    - brew install applesimutils --HEAD
    - cd test
    - npm install        
    - detox build --configuration ios.sim.release
    script:
    - CONF=ios.sim.release npx mocha Detox_helper_test.js

  - language: android
    env:
    - REACT_NATIVE_VERSION=0.59.4
    android:
    components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-26
    - sys-img-x86-android-28
    install:
    - yes | sdkmanager "platforms;android-28"    
    - npm install -g react-native-cli 
    - npm install -g detox-cli
    - cd test
    - npm install

    # Workaround until react android issue will be fixed - react-native: 0.55
    - mv node_modules/react-native/ReactAndroid/release.gradle node_modules/react-native/ReactAndroid/release.gradle.bak
    - cp extras/release.gradle node_modules/react-native/ReactAndroid/
    - cat node_modules/react-native/ReactAndroid/release.gradle
    - detox build --configuration android.emu.release
    script:
    - CONF=android.emu.release npx mocha Detox_helper_test.js


before_install:
- nvm install 10
